use_frameworks!

platform :ios, '8.0'

target 'LMCFoundation_Example' do
  pod 'LMCFoundation', :path => '../'

  target 'LMCFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
